apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 80
  selector:
    app: webapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
        - image: seei/webapp:96dc2f2
          name: webapp
          env:
            - name: PASSENGER_APP_ENV
              value: production
          ports:
            - containerPort: 80
              name: webapp
          imagePullPolicy: Always
