apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: seei/webapp:0687e52
          command: ["/bin/bash", "./setup.production.sh"]
          env:
            - name: PASSENGER_APP_ENV
              value: production
      restartPolicy: Never
